name: merge

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: YOUR_SECRET_NAME

# open or update publishing PR when there is a push to main
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  main-to-published:
    runs-on: ubuntu-24.04
    if: github.repository_owner == 'docker'
    steps:
      - uses: actions/checkout@v4
        with:
          ref: published
      - name: Reset published branch
        run: |
          git fetch origin main:main
          git reset --hard main
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5e914681df9dc83aa4e4905692ca88beb2f9e91f
        with:
          delete-branch: false
          branch: published-update
          commit-message: publish updates from main
          labels: area/release
          title: publish updates from main
          body: |
            Automated pull request for publishing docs updates.
